package kipper.tools;

import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.Image;
import java.awt.Color;
import java.awt.Polygon;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.BoxLayout;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener ;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.ArrayList;
import kipper.Util;
import kipper.ships.*;

public class MaskTool
{
    public static void main(String[] argv)
    {
        JFrame frame;
        JButton btn;
        JComboBox<Ship> cbxShips;
        JPanel pane1, pane2;
        final JTextArea txt = new JTextArea("");
        final DrawPanel drawpanel = new DrawPanel(txt);


        Ship[] shipsData = new Ship[] {
            new Darkwing(0, 0, null),
            new Enterprise(0, 0, null),
            new TriangleMan(0, 0, null)};

		frame = new JFrame("mask tool");
		frame.setLayout(new BoxLayout(frame.getContentPane(), BoxLayout.Y_AXIS));

        pane1 = new JPanel();
        pane2 = new JPanel();

        cbxShips = new JComboBox<Ship>(shipsData);
        cbxShips.addActionListener(
			new ActionListener()
            {
				public void actionPerformed(ActionEvent e)
                {
                    JComboBox<Ship> cb = (JComboBox<Ship>)e.getSource();
					drawpanel.loadShip((Ship)cb.getSelectedItem());
				}
			}
        );
        cbxShips.setSelectedIndex(0);
        pane1.add(cbxShips);

		txt.setRows(10);
		txt.setColumns(50);
		txt.setLineWrap(true);
		pane2.add(txt);

		btn = new JButton("clear");
		btn.addActionListener(
			new ActionListener()
            {
				public void actionPerformed(ActionEvent evt)
                {
					txt.setText("");
					drawpanel.clearMask();
				}
			}
		);
		pane2.add(btn);

        frame.add(pane1);
		frame.add(drawpanel);
        frame.add(pane2);

		frame.pack();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}
}

class DrawPanel extends JPanel implements MouseListener, MouseWheelListener
{
    private Ship ship;
	private Polygon mask;
	private JTextArea txt;
	private int factor = 10;
    private int imgX, imgY, imgWidth, imgHeight;

	public DrawPanel(JTextArea t)
    {
		this.txt = t;
		addMouseListener(this);
		addMouseWheelListener(this);
	}

    public void loadShip(Ship ship)
    {
        this.ship = ship;
        this.mask = ship.getDefaultMask();
        txt.setText(getMaskCode());
        repaint();
    }

    public void clearMask()
    {
        this.mask = new Polygon();
        txt.setText(getMaskCode());
        repaint();
    }

	public void paint(Graphics g)
    {
		super.paint(g);

        if (ship == null) {
            return;
        }

        imgWidth = ship.getImage().getWidth(this) * factor;
        imgHeight = ship.getImage().getHeight(this) * factor;

        imgX = getWidth() / 2 - imgWidth / 2;
        imgY = getHeight() / 2 - imgHeight / 2;

		g.setColor(Color.WHITE);
		g.fillRect(0, 0, getWidth(), getHeight());

		g.drawImage(ship.getImage(), imgX, imgY, imgWidth, imgHeight, this);

        // Display grid lines
		// g.setColor(Color.BLACK);
        // for (int y = imgY; y <= imgHeight + imgY; y += factor) {
            // for (int x = imgX; x <= imgWidth + imgX; x += factor) {
                // g.drawRect(x, y, factor, factor);
            // }
        // }

        Polygon scaledMask = getScaledMask();
		g.setColor(Color.GRAY);
		g.drawPolygon(scaledMask);
		g.setColor(Color.RED);
		for (int i = 0; i < scaledMask.npoints; i++) {
			g.fillRect(scaledMask.xpoints[i], scaledMask.ypoints[i], 6, 6);
        }
	}

    public Polygon getScaledMask()
    {
        Polygon result = new Polygon();
        for (int i = 0; i < mask.npoints; i++) {
            int x = mask.xpoints[i] * factor + imgX;
            int y = mask.ypoints[i] * factor + imgY;
            result.addPoint(x, y);
        }
        return result;
    }

	public void mouseReleased(MouseEvent evt)
    {
        int x = (evt.getX() - imgX) / factor;
        int y = (evt.getY() - imgY) / factor;
		mask.addPoint(x, y);
        txt.setText(getMaskCode());
        repaint();
	}

    public void mouseWheelMoved(MouseWheelEvent e)
    {
        factor += -e.getWheelRotation();
        factor = Math.max(factor, 1);
        factor = Math.min(factor, 30);
        repaint();
    }

    String getMaskCode()
    {
		List<Object> sb = new ArrayList<Object>();
		sb.add("// Generated by mask tool\n");
		sb.add("public Polygon getDefaultMask()\n{\n    return new Polygon(new int[] {");

        List<Object> xz = new ArrayList<Object>();
		for (int i = 0; i < mask.npoints; i++) {
			xz.add(mask.xpoints[i]);
		}
		sb.add(Util.join(xz, ", "));
        sb.add("}, new int[] {");

        xz = new ArrayList<Object>();
		for (int i = 0; i < mask.npoints; i++) {
            xz.add(mask.ypoints[i]);
		}
        sb.add(Util.join(xz, ", "));
        sb.add("}, ");
        sb.add(mask.npoints);
        sb.add(");\n}");
        return Util.join(sb, "");
    }

    public int getWidth() { return 800; }
    public int getHeight() { return 600; }
	public Dimension getMinimumSize() { return new Dimension(getWidth(), getHeight()); }
	public Dimension getPreferredSize() { return getMinimumSize(); }

	public void mouseExited(MouseEvent e) {}
	public void mouseEntered(MouseEvent e) {}
	public void mouseClicked(MouseEvent e) {}
    public void mousePressed(MouseEvent e) {}
}
